name: Build & Deploy ASP.NET Framework via MSDeploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet Packages
        run: nuget restore TestingApp.sln

      - name: Build with MSBuild
        run: msbuild TestingApp.sln /p:Configuration=Release

      - name: Publish via MSDeploy
        shell: cmd
        run: |
            "C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe" ^
              -verb:sync ^
              -source:contentPath=".\TestingApp\bin\Release\publish" ^
              -dest:contentPath="TestingApp",computerName="%DEPLOY_SERVER%",userName="%DEPLOY_USER%",password="%DEPLOY_PASS%",authType="Basic" ^
              -allowUntrusted
        env:
            DEPLOY_SERVER: ${{ secrets.DEPLOY_SERVER }}
            DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
            DEPLOY_PASS: ${{ secrets.DEPLOY_PASS }}
