name: Build & Deploy ASP.NET Core via MSDeploy

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet packages
        shell: cmd
        run: nuget restore TestingApp.sln

      - name: Package with MSBuild (Web Deploy)
        shell: cmd
        run: >
          msbuild ".\TestingApp\TestingApp.csproj"
          /p:Configuration=Release
          /p:DeployOnBuild=true
          /p:WebPublishMethod=Package
          /p:PackageAsSingleFile=true
          /p:PackageLocation="%GITHUB_WORKSPACE%\artifacts\TestingApp.zip"
          /p:SkipInvalidConfigurations=true
          /p:PackageParameters="IIS Web Application Name=TestingApp

      - name: Publish package via MSDeploy
        shell: cmd
        env:
          DEPLOY_SERVER: 70.153.16.192
          DEPLOY_SITE: TestingApp
          DEPLOY_USER: deployuser
          DEPLOY_PASS: deploy123!
        run: >
          "C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe"
          -verb:sync
          -source:package="%GITHUB_WORKSPACE%\artifacts\TestingApp.zip"
          -dest:auto,computerName="https://%DEPLOY_SERVER%:8172/msdeploy.axd?site=%DEPLOY_SITE%",userName="%DEPLOY_USER%",password="%DEPLOY_PASS%",authType="Basic"
          -setParam:name="IIS Web Application Name",value="TestingApp"
          -allowUntrusted -enableRule:AppOffline
