name: Build & Deploy ASP.NET Framework via MSDeploy

on:
  push:
    branches:
      - "fix/ci-cd-integration"

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet Packages
        run: nuget restore TestingApp.sln

      - name: Build & Publish (Folder)
        shell: cmd
        run: >
          msbuild ".\TestingApp\TestingApp.csproj"
          /p:Configuration=Release
          /p:WebPublishMethod=FileSystem
          /p:DeleteExistingFiles=True
          /p:PublishUrl="%GITHUB_WORKSPACE%\TestingApp\bin\Release\publish"
      
      - name: Verify publish output exists
        shell: cmd
        run: |
          echo WORKSPACE=%GITHUB_WORKSPACE%
          if not exist "%GITHUB_WORKSPACE%\TestingApp\bin\Release\publish\nul" (
            echo Publish folder MISSING
            dir /s "%GITHUB_WORKSPACE%\TestingApp\bin\Release"
            exit /b 1
          )
          dir /s "%GITHUB_WORKSPACE%\TestingApp\bin\Release\publish"
      
      # (Opsional) cek port 8172 dari runner
      - name: Check 8172 reachability
        shell: powershell
        run: Test-NetConnection 70.153.16.192 -Port 8172

      - name: Publish via MSDeploy
        shell: cmd
        run: >
          "C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe"
          -verb:sync
          -source:contentPath="%GITHUB_WORKSPACE%\TestingApp\bin\Release\publish"
          -dest:iisApp="TestingApp",computerName="https://70.153.16.192:8172/msdeploy.axd?site=TestingApp",userName="deployuser",password="deploy123!",authType="Basic"
          -allowUntrusted
        env:
          DEPLOY_SERVER: ${{ secrets.DEPLOY_SERVER }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_PASS: ${{ secrets.DEPLOY_PASS }}
