name: Build & Deploy ASP.NET Framework - Package + AppOffline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET (SDK 9)
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Restore
        run: dotnet restore ".\TestingApp\TestingApp.csproj"

      - name: Build Package
        shell: pwsh
        run: |
          & "C:\Program Files\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\MSBuild.exe" .\TestingApp\TestingApp.csproj /t:Package /p:Configuration=Release /p:PackageLocation="$env:GITHUB_WORKSPACE\artifacts\TestingApp.zip"

      - name: Verify Package Exists
        shell: cmd
        run: |
          if not exist "%GITHUB_WORKSPACE%\artifacts\TestingApp.zip" (
            echo Package MISSING
            exit /b 1
          )
          dir /s "%GITHUB_WORKSPACE%\artifacts"

      - name: Deploy Package to IIS Site
        shell: cmd
        run: >
          "C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe"
          -verb:sync
          -source:package="%GITHUB_WORKSPACE%\artifacts\TestingApp.zip"
          -dest:iisApp="TestingApp",computerName="https://70.153.16.192:8172/msdeploy.axd",userName="deployuser",password="deploy123!",authType="Basic"
          -enableRule:AppOffline -allowUntrusted -verbose
