name: Build & Deploy ASP.NET Core via MSDeploy

on:
  push:
    branches: [ "fix/ci-cd-integration" ]

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET (SDK 9)
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore ".\TestingApp\TestingApp.csproj"

      - name: Publish (ASP.NET Core)
        run: >
          dotnet publish ".\TestingApp\TestingApp.csproj"
          -c Release
          -o "%GITHUB_WORKSPACE%\artifacts\publish"
          --nologo

      - name: Verify publish output exists
        shell: cmd
        run: |
          echo WORKSPACE=%GITHUB_WORKSPACE%
          if not exist "%GITHUB_WORKSPACE%\artifacts\publish\nul" (
            echo Publish folder MISSING
            dir /s "%GITHUB_WORKSPACE%\artifacts"
            exit /b 1
          )
          dir /s "%GITHUB_WORKSPACE%\artifacts\publish"

      - name: Install Web Deploy (msdeploy)
        shell: powershell
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          if (!(Get-Command choco -ErrorAction SilentlyContinue)) {
            iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
          }
          choco install webdeploy --yes --no-progress

      - name: Check 8172 reachability (optional)
        shell: powershell
        run: Test-NetConnection $env:DEPLOY_SERVER -Port 8172
        env:
          DEPLOY_SERVER: ${{ secrets.DEPLOY_SERVER }}

      - name: Publish via MSDeploy
        shell: cmd
        run: >
          "C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe"
          -verb:sync
          -source:contentPath="%GITHUB_WORKSPACE%\TestingApp\bin\Release\publish"
          -dest:iisApp="TestingApp",computerName="https://70.153.16.192:8172/msdeploy.axd?site=TestingApp",userName="deployuser",password="deploy123!",authType="Basic"
          -allowUntrusted -verbose
