name: Build & Deploy ASP.NET Framework via MSDeploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET (SDK 9)
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Restore
        run: dotnet restore ".\TestingApp\TestingApp.csproj"

      - name: Publish (ASP.NET Core)
        shell: pwsh
        run: >
          dotnet publish .\TestingApp\TestingApp.csproj
          -c Release
          -o "$env:GITHUB_WORKSPACE\artifacts\publish"
          --nologo

      - name: Verify publish output exists
        shell: cmd
        run: |
          echo WORKSPACE=%GITHUB_WORKSPACE%
          if not exist "%GITHUB_WORKSPACE%\artifacts\publish\*" (
            echo Publish folder MISSING
            dir /s "%GITHUB_WORKSPACE%\artifacts"
            exit /b 1
          )
          dir /s "%GITHUB_WORKSPACE%\artifacts\publish"

      - name: Publish via MSDeploy
        shell: cmd
        run: >
          "C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe"
          -verb:sync
          -source:contentPath="%GITHUB_WORKSPACE%\artifacts\publish"
          -dest:contentPath="C:\inetpub\TestingApp",computerName="https://70.153.16.192:8172/msdeploy.axd?site=TestingApp",userName="deployuser",password="deploy123!",authType="Basic"
          -allowUntrusted -verbose
