name: Build & Deploy ASP.NET Framework via MSDeploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet Packages
        run: nuget restore TestingApp.sln

      - name: Build with MSBuild
        run: msbuild TestingApp.sln /p:Configuration=Release

      - name: Publish via MSDeploy
        shell: powershell
        run: |
          $msdeploy = "C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe"
          $sourcePath = "$(Get-Location)\TestingApp\bin\Release\publish"
          & "$msdeploy" -verb:sync `
            -source:contentPath="$sourcePath" `
            -dest:contentPath="TestingApp",computerName="https://70.153.16.235:8172/msdeploy.axd?site=TestingApp",userName="deployuser",password="deploy123!",authType="Basic" `
            -allowUntrusted
