name: Build & Deploy ASP.NET Core via MSDeploy

on:
  push:
    branches: [ "fix/ci-cd-integration" ]

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET (SDK 9)
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Restore
        run: dotnet restore ".\TestingApp\TestingApp.csproj"

      - name: Publish (ASP.NET Core)
        shell: pwsh
        run: >
          dotnet publish .\TestingApp\TestingApp.csproj
          -c Release
          -o "$env:GITHUB_WORKSPACE\artifacts\publish"
          --nologo

      - name: Create MSDeploy package
        shell: cmd
        run: >
          "C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe"
          -verb:sync
          -source:dirPath="%GITHUB_WORKSPACE%\artifacts\publish"
          -dest:package="%GITHUB_WORKSPACE%\artifacts\TestingApp.zip"
          -verbose

      - name: Publish via MSDeploy
        shell: cmd
        run: >
          "C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe" ^
            -verb:sync ^
            -source:package="%GITHUB_WORKSPACE%\artifacts\TestingApp.zip" ^
            -dest:iisApp="TestingApp",computerName="https://70.153.16.192:8172/msdeploy.axd?site=TestingApp",userName="deployuser",password="deploy123!",authType="Basic" ^
            -enableRule:AppOffline -enableRule:DoNotDeleteRule -allowUntrusted -verbose
