name: Build & Deploy ASP.NET Framework via MSDeploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet Packages
        run: nuget restore TestingApp.sln

      - name: Build & Publish
        run: >
          msbuild TestingApp.sln
          /p:Configuration=Release
          /p:DeployOnBuild=true
          /p:PublishProfile=FolderProfile
          /p:PublishUrl=".\TestingApp\bin\Release\publish"

      # - name: Deploy via MSDeploy
      #   shell: cmd
      #   run: >
      #     "C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe"
      #     -verb:sync
      #     -source:contentPath=".\TestingApp\bin\Release\publish"
      #     -dest:contentPath="TestingApp",
      #     computerName="https://70.153.16.192:8172/msdeploy.axd?site=TestingApp",
      #     userName="deployuser",
      #     password="deploy123!",
      #     authType="Basic"
      #     -allowUntrusted

      # - name: Publish via MSDeploy
      #   shell: cmd
      #   run: >
      #     "C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe"
      #     -verb:sync
      #     -source:contentPath=".\TestingApp\bin\Release\publish"
      #     -dest:contentPath="TestingApp",computerName="https://70.153.16.192:8172/msdeploy.axd?site=TestingApp",userName="deployuser",password="deploy123!",authType="Basic"
      #     -allowUntrusted
      #   env:
      #     DEPLOY_SERVER: ${{ secrets.DEPLOY_SERVER }}
      #     DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
      #     DEPLOY_PASS: ${{ secrets.DEPLOY_PASS }}
      - name: Deploy to IIS via Web Deploy
        run: |
          "C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe" -verb:sync ^
          -source:contentPath=".\TestingApp\bin\Release\publish" ^
          -dest:iisApp="TestingApp",computerName="https://${{ env.DEPLOY_SERVER }}:8172/msdeploy.axd?site=TestingApp",userName="${{ env.DEPLOY_USER }}",password="${{ env.DEPLOY_PASS }}",authType="Basic" ^
          -allowUntrusted -enableRule:AppOffline
        shell: cmd
        env:
          DEPLOY_SERVER: 70.153.16.192
          DEPLOY_USER: deployuser
          DEPLOY_PASS: deploy123!
