name: Deploy ASP.NET to IIS

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch

jobs:
  build-and-deploy:
    # This job runs on the self-hosted runner, which has access to your IIS server.
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.x" # Replace with your .NET version

      - name: Restore dependencies
        run: dotnet restore

      - name: Build and publish
        run: dotnet publish -c Release -o ${{ github.workspace }}/publish

      - name: Deploy to IIS using Web Deploy
        uses: ChristopheLav/iis-deploy@v1 # Use a community-developed Web Deploy action
        with:
          website-name: "TestingApp" # Replace with your IIS site name
          msdeploy-service-url: https://70.153.16.192:8172/msdeploy.axd
          msdeploy-username: deployuser
          msdeploy-password: deploy123!
          source-path: ${{ github.workspace }}/publish # The published output
          skip-extra-files: false
          # You can add more Web Deploy parameters here if needed
          # e.g., enable-app-offline: true to take the site offline during deployment
